prefix = '.'
stop-words = 'stopwords.txt'

dataset = 'Dataset'
corpus = 'line.toml'
index = 'idx'

query-judgements = 'train_qrel'
[[analyzers]]
method = 'ngram-word'
ngram = 1
filter = 'default-unigram-chain'
