prefix = '.'
stop-words = 'stopwords.txt'

dataset = 'Academic_papers'
corpus = 'line.toml'
index = 'idx'

query-judgements = 'Academic_papers/train_queries_qrel2'
[[analyzers]]
method = 'ngram-word'
ngram = 1
filter = 'default-chain'
